### ISSUE TITLE
MegaEvolve not making any sound

### ISSUE THREAD

**Issue by FrancisPerulero** [StrangeOne101/PixelTweaks#12]
## Description
When mega-evolving a Pokémon in battle, it doesn't play any sound, even after following the resource pack steps, even though the message displays correctly.

## How to reproduce
1. Enter a battle
2. MegaEvolve a Pokemon
3. No make any sound

## Context
Pixelmon Version: 9.1.7
PixelTweaks Version: 1.7.1
Server or Single Player: Singleplayer

Additional Context: -

**Comment by StrangeOne101** [comment]
Could you send me a version of the resource pack you're using so I can do some testing with it?

**Comment by StrangeOne101** [comment]
Cannot replicate. Your resource pack just didn't have the Mega Evolve thing setup right. The JSON file was a txt file
