### ISSUE TITLE
Weather's ability no making a sound

### ISSUE THREAD

**Issue by FrancisPerulero** [StrangeOne101/PixelTweaks#13]
## Description
I'm not sure if this is a bug or if it's not configured to work this way, but when Pokémon enter the battle and summon weather with their ability, they don't play any sound. They should make the same sound that plays when the message for weather invoked by an attack appears

## How to reproduce
1. Enter a battle with Tyranitar o Pelipper
2. The weather changes and its show a message but dont play any sound
3. xxxxx

## Context
Pixelmon Version: 9.1.7
PixelTweaks Version: 1.7.1
Server or Single Player: Singleplayer

Additional Context: -

**Comment by StrangeOne101** [comment]
What resource pack are you using?

**Comment by FrancisPerulero** [comment]
I'm using a personal and customized one myself, it has the following weather's sounds:  
"se/weather_rainy": {
    "sounds": [{
      "name": "pixeltweaks:sfx/weather_rainy",
      "stream": true
    }],
    "replace": true 
  },
  "se/weather_sunny": {
    "sounds": [{
      "name": "pixeltweaks:sfx/weather_sunny",
      "stream": true
    }],
    "replace": true 
},
  "se/weather_sandstorm": {
    "sounds": [{
      "name": "pixeltweaks:sfx/weather_sandstorm",
      "stream": true
    }],
    "replace": true 
},
  "se/weather_hail": {
    "sounds": [{
      "name": "pixeltweaks:sfx/weather_hail",
      "stream": true
    }],
    "replace": true 
}"
In the pixeltweaks's folder with others sfx sounds.

**Comment by StrangeOne101** [comment]
Can you send me the resource pack you use for this via discord so I can test?

**Comment by StrangeOne101** [comment]
Seems to only affect abilities that cause weather. Moves that create weather appear to be fine.

I've fixed it for Drizzle, Drought and Sand Stream

**Comment by StrangeOne101** [comment]
Fixed in 1.9.5
