### ISSUE TITLE
NPC Battles terminate after one defeated pokémon

### ISSUE THREAD

**Issue by DigitalMonkeyMaster** [StrangeOne101/PixelTweaks#17]
## Description
Myself and a few players got a crash while playing on my custom modpack server which has no recent pack updates.
When defeating a pokémon during an NPC battle, the battle ends.
This occurs on both the multiplayer server AND in a single player game for myself and other players.

## How to reproduce
1. Start a fight with a custom npc who has 2+ pokémon
2. Defeat the first pokémon
3. Battle terminates with errors
<img width="470" alt="report crash to devs" src="https://github.com/StrangeOne101/PixelTweaks/assets/73271713/251dca43-00b0-41fc-82b6-3831ca8bd530">

## Context
Pixelmon Version: 1.35
PixelTweaks Version: 1.10.0
Server or Single Player: Both

Additional Context:
I believe this only happens with custom NPC's However I will check this against spawned NPC's shortly and update.

Log from the server here:
[pixeltweak crash 020122024.txt](https://github.com/StrangeOne101/PixelTweaks/files/13814168/pixeltweak.crash.020122024.txt)
Modpack link: [https://www.curseforge.com/minecraft/modpacks/pixeltechcraft/files/5027386](url)

You can try it out yourself on the public server (available in the multiplayer section)

**Comment by StrangeOne101** [comment]
Thanks for the report. Could you please clarify which version of Pixelmon you are using?

**Comment by DigitalMonkeyMaster** [comment]
Apologies, I've just realized I posted the pack version for pixelmon 😓 
The Pixelmon version is 1.16.5-9.1.10

**Comment by StrangeOne101** [comment]
Fixed in 9ad7b323379cd4c3073734c1a7590c007a062f5a (v1.10.1)
