### ISSUE TITLE
Two Pixeltweaks Related Crashes with Identical Symptoms

### ISSUE THREAD

**Issue by Spydrouge** [StrangeOne101/PixelTweaks#18]
## Description
The game will crash and, when the loader reboots, it will display a textbox saying that it crashed because it is missing a field "BATTLE_MUSIC."

This is caused by one of two situations
1. There is a mismatch between the Pixeltweaks version and the Pixelmon version.
2. pokedrops.json contains any invalid json

## How to reproduce

Bug One:
1. Install a version of Pixeltweaks that is fully updated, but fail to update the Pixelmon version
2. Run the game, attempt to battle with a pokemon.
3. Game crashes immediately with a text box blaming BATTLE_MUSIC

But Two:
1. Install Pixeltweak and Pixelmon as normal. Ensure versions match.
2. Create a datapack, and in it, put invalid json in pokedrops.json. This could be as simple as an extra comma where a comma should not be.
3. Run the game and attempt to battle with a pokemon
4. Game crashes immediately with a text box blaming BATTLE_MUSIC

## Expected Behavior
Should not cause a crash, or, if it does, should crash with a correct and informative error message.

## Context
Bug One:
Pixelmon Version: 1.16.10
PixelTweaks Version: 1.10.2 (mismached)

Bug Two:
Pixelmon Version: 1.16.10
PixelTweaks Version: 1.10.1 (matching)

Server or Single Player: Singleplayer

**Comment by StrangeOne101** [comment]
Can you give specific versions of Pixelmon this is occurring on?

I assume you mean 9.1.10

**Comment by StrangeOne101** [comment]
Closed due to inactivity and because this doesn't effect the latest version of PixelTweaks
