### ISSUE TITLE
Server crash when i use this mod

### ISSUE THREAD

**Issue by PanetiX** [StrangeOne101/PixelTweaks#5]
## Description
Server crash when i use this mod. 

## How to reproduce
1. install the mod as it should
2. play some time, the server will crash
3. need to delete the mod and upload a backup from world (just remove the mod the server will crash until i upload a world which was backedup befor using the mod)

## Context
Pixelmon Version: Pixelmon-1.16.5-9.1.5-universal
PixelTweaks Version: 1.4
Server or Single Player: Server - arclight-forge-1.16.5-1.0.24

Additional Context:
Full crash-log: https://pastebin.com/jjjUwetq

**Comment by StrangeOne101** [comment]
I've been looking into this in the background as well as I've noticed a few people recently in the Pixelmon discord have this issue. I believe it's to do with Zygarde cells, but for the specifics, I'm not sure

Thanks for the bug report and log. I'm investigating

**Comment by StrangeOne101** [comment]
I believe this is fixed in 52d96c4ac949789c1e8661a31e0a20845dde4eab (v1.4.1), so can you confirm this?

**Comment by StrangeOne101** [comment]
Fixed in 52d96c4ac949789c1e8661a31e0a20845dde4eab
